apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: christoph-demo1-service
  title: Christophs Demo 1 Service
  description: |
    This is a small demo service with annotations for:
    - Tekton (filtered by the namespace below)
  links:
    - title: My Janus notes
      url: https://github.com/ciiay/janus
  annotations:
    backstage.io/source-location: url:https://github.com/ciiay/janus/blob/main/test-catalog/components/christoph-demo1-service.yaml
    backstage.io/view-url: https://github.com/ciiay/janus/blob/main/test-catalog/components/christoph-demo1-service.yaml
    backstage.io/edit-url: https://github.com/ciiay/janus/edit/main/test-catalog/components/christoph-demo1-service.yaml
    backstage.io/techdocs-ref: url:https://github.com/ciiay/janus/tree/main/techdocs/christoph-demo
    github.com/project-slug: ciiay/janus
    backstage.io/kubernetes-id: christoph-demo1-service
    backstage.io/kubernetes-namespace: christoph-backstage-test
    janus-idp.io/tekton: christoph-demo1-service
  tags:
    - christoph-demo
spec:
  type: service
  owner: user:ciiay
  lifecycle: experimental
  system: christoph-demo-system
