apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: christoph-demo3-service
  title: Christophs Demo 3 Service
  description: |
    This is a small demo service with annotations for:
    - Tekton (with namespace and label selector)
  links:
    - title: My Janus notes
      url: https://github.com/jerolimov/janus
  annotations:
    backstage.io/source-location: url:https://github.com/jerolimov/janus/blob/main/test-catalog/components/christoph-demo1-service.yaml
    backstage.io/techdocs-ref: dir:../../../techdocs/christoph-demo
    github.com/project-slug: jerolimov/janus
    backstage.io/kubernetes-id: christoph-demo3-service
    backstage.io/kubernetes-namespace: christoph-backstage-test
    backstage.io/kubernetes-label-selector: component=christoph-demo3-service
    janus-idp.io/tekton: christoph-demo3-service
  tags:
    - christoph-demo
spec:
  type: service
  owner: user:ciiay
  lifecycle: experimental
  system: christoph-demo-system
  subcomponentOf: christoph-demo2-service
